#!/bin/bash


# Build telegraf config
cat << EOF > /etc/telegraf/telegraf.conf
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true

[[outputs.influxdb]]
EOF

# Add InfluxDB URL
echo -n 'urls = ["' >> /etc/telegraf/telegraf.conf
echo -n $INFLUXDB_URL >> /etc/telegraf/telegraf.conf
echo '"]' >> /etc/telegraf/telegraf.conf

# Finish config
cat << EOF >> /etc/telegraf/telegraf.conf
  database = "piaware"
  skip_database_creation = false
  timeout = "5s"

# Influx HTTP write listener
[[inputs.http_listener]]
  service_address = ":8186"
  read_timeout = "10s"
  write_timeout = "10s"
EOF

# Start telegraf
telegraf --config /etc/telegraf/telegraf.conf --test
telegraf --config /etc/telegraf/telegraf.conf