#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

exec \
  /usr/local/bin/telegraf \
    --config /etc/telegraf/telegraf.conf \
    2>&1 | awk -W interactive '{print "[telegraf] " $0}'
