#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

exec \
  /usr/bin/python3 \
    /piaware2influx.py \
    -ds "${DUMP1090_HOST}" \
    2>&1 | awk -W interactive '{print "[piaware2influx] " $0}'
