#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set -eo pipefail

exec \
  /opt/piaware2influx/piaware2influx \
  -ds "${DUMP1090_HOST}" \
  2>&1 | awk -W interactive '{print "[piaware2influx] " $0}'
