#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Check to make sure the correct command line arguments have been set
EXITCODE=0
echo -ne "\e[31m"
if [ -z "${INFLUXDB_URL+x}" ]; then
  echo "ERROR: INFLUXDB_URL environment variable not set"
  EXITCODE=1
fi
if [ -z "${DUMP1090_HOST+x}" ]; then
  echo "ERROR: DUMP1090_HOST environment variable not set"
  EXITCODE=1
fi
if [ -z "${VERBOSE_LOGGING+x}" ]; then
  VERBOSE_LOGGING=False
fi
if [ -z "${INFLUXDB_DB+x}" ]; then
  INFLUXDB_DB="piaware"
fi
echo -ne "\e[0m"
if [ $EXITCODE -ne 0 ]; then
  exit 1
fi

# Set up timezone
if [ -z "${TZ}" ]; then
  echo -ne "\e[33m"
  echo "WARNING: TZ environment variable not set"
  echo -ne "\e[0m"
else
  ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
fi

# Build telegraf config
{
echo """
[global_tags]

[agent]
  interval = \"10s\"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = \"0s\"
  flush_interval = \"10s\"
  flush_jitter = \"0s\"
  precision = ""
"""

if [ -z "${VERBOSE_LOGGING+x}" ]; then
  echo '  debug = false'
  echo '  quiet = true'
else
  echo '  debug = true'
  echo '  quiet = false'
fi

echo """
  logfile = \"\"
  hostname = \"\"
  omit_hostname = true

[[outputs.influxdb]]
"""

# Add InfluxDB URL
echo -n '  urls = ["'
echo -n "${INFLUXDB_URL}"
echo '"]'

# InfluxDB database name
echo -n '  database = "'
echo -n "${INFLUXDB_DB}"
echo '"'

# InfluxDB auth, if specified
if [ -n "${INFLUXDB_USER+x}" ]; then
  echo -n '  username = "'
  echo -n "${INFLUXDB_USER}"
  echo '"'
fi
if [ -n "${INFLUXDB_PASS+x}" ]; then
  echo -n '  password = "'
  echo -n "${INFLUXDB_PASS}"
  echo '"'
fi

# Finish config
echo """
  skip_database_creation = false
  timeout = \"5s\"

# Influx HTTP write listener
[[inputs.influxdb_listener]]
  service_address = \":8186\"
  read_timeout = \"10s\"
  write_timeout = \"10s\"
"""

} > /etc/telegraf/telegraf.conf
